### ISSUE TITLE
Scanning/Bestiary Issue

### ISSUE THREAD

**Issue by wasniahC** [Finnerex/MissileTurret#8] opened 2024-04-04 13:07 UTC
When scanning a missile turret, it behaves differently to turrets/landmines; rather than just showing the name, it does the "Info sent to bestiary!" message (if it's the first time).

From then on, the bestiary is broken, and just shows this instead of its entries:
![image](https://github.com/Finnerex/MissileTurret/assets/57833420/f10deed3-9185-427f-91db-a0d8d0447ebd)

Just aside from the bestiary being janky, I would probably suggest trying to change it so it doesn't send anything to the bestiary at all. It would integrate smoother with the game if scanning them works the same as scanning other traps (turret/landmine)

**Comment by Silhygames** [comment] 2024-05-11 15:32
Can confirm; Just went through my whole enemy list and found it was missile turrets that was breaking the bestiary

**Comment by Finnerex** [comment] 2024-05-11 19:23
I looked in to this a little bit. I can't seem to find any reason that it should say the info sent message. I'll keep looking, but if anybody finds anything about this, please let me know.

**Comment by Silhygames** [comment] 2024-05-11 20:52
Yeah, no idea on that front. Are you in the Lethal Company Modding Discord? They might be able to help. We've got a lot of modders who have had similar issues with monsters and had to correct for them, there, so maybe someone knows how to fix it.

**Comment by Silhygames** [comment] 2024-05-16 18:21
You know, I was just thinking about this. No idea how similar the turrets are to scrap in Unity, but have you considered removing the scannode from the turret? Or maybe just moving it so the scannode is in an impossible-to-scan location, such as far below the turret, underneath the floor?

![image](https://github.com/Finnerex/MissileTurret/assets/154468048/722ca472-8ef2-4233-a61f-83c3b4ffbeed)


If the player can't scan the turret, then it won't break the bestiary. And frankly, turrets can't normally be scanned, anyways, right?

**Comment by Finnerex** [comment] 2024-05-16 20:00
I think normal turrets can be scanned. I still want missile turrets to be scanned, I just don't know why its trying to give it a bestiary entry when it shouldn't have one, just like normal turrets.

**Comment by Silhygames** [comment] 2024-05-16 20:10
Could be a way of bypassing the issue for the moment until you find the root cause, though. Still recommend bugging people in the modding discord, too.

**Comment by Finnerex** [comment] 2024-05-16 20:15
I just figured out a fix, pushing changes soon. For anyone interested, this was fixed by setting the Creature Scan ID in the Scan Node Properties to -1

**Closed by Finnerex** 2024-05-16 20:15 UTC
